### PR TITLE
Release 0.3.13 :rocket:

### PR DESCRIPTION
**Pull request by aenario**
Not sure if I am suppose to push directly to master or how it is done.

### CODE REVIEW

**Comment by nono** [comment]
@aenario you should update the ChangeLog too

**Comment by CPatchane** [comment]
Agree with @nono, the `CHANGELOG.md` need to be updated (at least) at each release.

**Comment by aenario** [comment]
Added changelog and docs changes.

**Comment by nono** [comment]
At the bottom of the ChangeLog, there are some links to update too :wink:

**Pull request merged**
