### PR TITLE
Add .npmignore to reduce weight :nut_and_bolt:

### PR DESCRIPTION
**Pull request by kosssi**
```
$ ls -al
total 448
drwxr-xr-x   19 kosssi  staff     646  1 fév 09:09 .
drwxr-xr-x  179 kosssi  staff    6086  1 fév 09:09 ..
-rw-r--r--    1 kosssi  staff     114 31 jan 17:59 .babelrc
-rw-r--r--    1 kosssi  staff     702 31 jan 17:59 .npmignore
-rw-r--r--    1 kosssi  staff    2049 31 jan 17:59 .travis.yml
-rw-r--r--    1 kosssi  staff    6062 31 jan 17:59 CONTRIBUTING.md
-rw-r--r--    1 kosssi  staff    1074 31 jan 17:59 LICENSE
-rw-r--r--    1 kosssi  staff    3961 31 jan 17:59 README.md
drwxr-xr-x    3 kosssi  staff     102 31 jan 17:59 _workspace
drwxr-xr-x    6 kosssi  staff     204  1 fév 09:09 dist
drwxr-xr-x    7 kosssi  staff     238  1 fév 09:09 docs
-rw-r--r--    1 kosssi  staff     352 31 jan 17:59 index.html
-rw-r--r--    1 kosssi  staff     235 31 jan 17:59 manifest.webapp
-rw-r--r--    1 kosssi  staff     123 31 jan 17:59 mocha-webpack.opts
-rw-r--r--    1 kosssi  staff    4088  1 fév 09:09 package.json
drwxr-xr-x   14 kosssi  staff     476  1 fév 09:09 src
drwxr-xr-x    8 kosssi  staff     272  1 fév 09:09 test
-rw-r--r--    1 kosssi  staff    1330 31 jan 17:59 webpack.config.js
-rw-r--r--    1 kosssi  staff  176574 31 jan 17:59 yarn.lock
```

### CODE REVIEW

**Comment by kosssi** [comment]
When you publish a release on npm this file can exclude file or folder like `.gitignore`.

**Comment by nono** [comment]
The npmignore is quite long. Maybe we can use whitelisting instead of blacklisting. We may put the files to include in package.json

**Comment by nono** [comment]
Cf https://docs.npmjs.com/files/package.json#files

**Comment by kosssi** [comment]
@nono It's a good idea. You know an example?

Like that:
```
files: [
  "dist",
  "docs"
]
```

**Comment by nono** [comment]
I don't have an example. But yes, it's like this.

**Pull request merged**
