### PR TITLE
chore(nvmrc): Set Node 16

### PR DESCRIPTION
**Pull request by trollepierre**
any idea why pipeline fails :(

### CODE REVIEW

**Comment by trollepierre** [comment]
@Crash--

**Comment by trollepierre** [comment]
@Crash-- ?

**Review by JF-Cozy — COMMENTED** [review]
update travis ?

**Comment by trollepierre** [comment]
@JF-Cozy : already updated: https://github.com/cozy/cozy-client-js/blob/master/.travis.yml#L3

**Review by JF-Cozy — APPROVED** [review]

**Pull request merged**
