### PR TITLE
Add an option to not sanitize the filenames

### PR DESCRIPTION
**Pull request by nono**
It is useful for the cozy-desktop client as we want to have exactly the same filenames on the client and on the cozy instance.

### CODE REVIEW

**Comment by ptbrowne** [comment]
No tests ?

**Comment by ptbrowne** [comment]
Ping ?

**Comment by nono** [comment]
This PR was a work in progress for a cozy-desktop issue. I'm not working on cozy-desktop, and @sebn or @taratatach will continue to work on it after the new watcher has been releases. So, for the moment, it is in pause.

**Comment by taratatach** [comment]
Closing in favor of https://github.com/cozy/cozy-client-js/pull/290

**Pull request closed without merging**
