### PR TITLE
[release] v0.3.0

### PR DESCRIPTION
**Pull request by enguerran**

### CODE REVIEW

**Comment by enguerran** [comment]
As soon as #161 is merged, this PR will contain only one release commit. Please, review.

**Comment by enguerran** [comment]
This is the Release's draft: https://github.com/cozy/cozy-client-js/releases/tag/untagged-4989827a5845836b0664

**Comment by gregorylegarec** [comment]
Don't forget the 🚀  emoji in your commit message

**Comment by enguerran** [comment]
Here we go!

**Pull request merged**
