### PR TITLE
[fix] Make sure FetchError has a proper message

### LINKED ISSUE #112: Error on invalid query should be more explicit
## Summary

Calling cozy.client.data.query with invalid parameters should return an explicit error message

## STR
```
cozy.client.data.query(myIndex, {}).then().catch((err) => { console.error(err);})
```

## Expected result

The full error returned by the server: `{"error":"missing_required_key","ok":false,"reason":"Missing required key: selector","status":"400"}`

## Actual result

Only an Error object, without name nor message.

## Version of CozyClientJs

0.1.7

### PR DESCRIPTION
**Pull request by sebn**
Should fix #112

### CODE REVIEW

**Comment by sebn** [comment]
Appvengers, any thought? 😃

**Comment by sebn** [comment]
Oops, forgot you were one of them @y-lohse.
Merging then.

**Comment by sebn** [comment]
@y-lohse I believe this issue appeared when we started subclassing `Error`. Extending built-in classes is officially unsupported in Babel and generally doesn't work as intended, requiring various fixes.

**Comment by y-lohse** [comment]
Gotcha, thanks!

**Pull request merged**
