### PR TITLE
Add intent transition handling

### PR DESCRIPTION
**Pull request by CPatchane**
Useful to 'animate' intent resizing using css transitions.

### CODE REVIEW

**Comment by y-lohse** [comment]
@CPatchane code looks good 👍 

Help me jog my memory though, when does this happen? When the service tells the client it wants to be displayed at a certain size, is that correct?

**Comment by CPatchane** [comment]
Exactly this point @y-lohse

**Comment by CPatchane** [comment]
[(5) [NUA-7] ETU je peux contacter le support directement depuis le nuage](https://trello.com/c/aGWhw9XW/541-5-nua-7-etu-je-peux-contacter-le-support-directement-depuis-le-nuage)

**Comment by gregorylegarec** [comment]
I really don't get why an intent service should provide a presentation information to the client ? Isn't only client's purpose ?

**Comment by CPatchane** [comment]
@gregorylegarec We could choose how the css is animated using CSS transition, couldn't we?

**Comment by gregorylegarec** [comment]
@CPatchane Ok thanks, let's go with it 👍

**Comment by y-lohse** [comment]
To be fair, this also bothers me a little. I think Claudy is an extreme use case of intents.
Theoretically speaking, would it be better if Claudy was distributed as a standalone js code, instead of an iframe? It could still use intents to do it's things, but only to manipulate data, while the resizing / animating / etc would be done on the client side and wouldn't event be in the intents?

(ping @CPatchane and @gregorylegarec so you get a notification just in case)

**Comment by gregorylegarec** [comment]
The more it grows, the more Claudy become extreme in many way.


@y-lohse @CPatchane
Maybe the need to pass this kind of data from the intente service means that our whole design is bad. But also, having a standalone Claudy would not solve those issues.
However, externalizing Claudy from Cozy-Bar looks like a good idea. Again, we are falling back to our modularization and code mutualization problems.

**Comment by CPatchane** [comment]
Agree with @gregorylegarec about separate Claudy would not solve issues about our current workflow.
However, I think we should see Claudy as a good example of extreme user of intents and a way to make it the most robust and reusable.

**Pull request merged**
